# Generated by Django 3.1.3 on 2020-11-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
