# Generated by Django 3.1.3 on 2021-02-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201210_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=428)),
                ('x1', models.DecimalField(decimal_places=14, max_digits=17)),
                ('x2', models.DecimalField(decimal_places=14, max_digits=17)),
                ('y1', models.DecimalField(decimal_places=14, max_digits=17)),
                ('y2', models.DecimalField(decimal_places=14, max_digits=17)),
                ('zoom', models.DecimalField(decimal_places=5, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Isolines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('date', models.DateTimeField()),
                ('type', models.IntegerField(max_length=1)),
                ('extentId', models.BigIntegerField(serialize=False)),
            ],
        ),
    ]
