# Generated by Django 3.1.6 on 2021-02-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210208_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='value',
            field=models.BinaryField(),
        ),
    ]
