# Generated by Django 3.1.3 on 2021-02-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_extent_isolines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolines',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
