# Generated by Django 3.1.3 on 2021-02-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210202_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
                ('interpolation_type', models.CharField(max_length=50)),
                ('extentId', models.BigIntegerField(serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Isolines',
        ),
    ]
