# Generated by Django 3.1.6 on 2021-03-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_researchzone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='type',
            new_name='kind',
        ),
    ]
