# Generated by Django 3.1.6 on 2021-05-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210305_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.researchzone'),
        ),
        migrations.AddField(
            model_name='researchzone',
            name='Extent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.extent'),
        ),
    ]
