# Generated by Django 3.1.6 on 2021-05-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210528_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='zone',
            new_name='Zone',
        ),
    ]
