# Generated by Django 3.1.3 on 2021-02-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210203_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='extentId',
        ),
        migrations.AddField(
            model_name='plot',
            name='Extent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.extent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
